# Created using wingetcreate

PackageIdentifier: AppleInc.iCloud
PackageVersion: 7.21.0.23
PackageLocale: en-US
Publisher: Apple Inc.
PackageName: iCloud
License: © 2012 Apple Inc. All Rights Reserved.
ShortDescription: iCloud Installer
ManifestType: defaultLocale
ManifestVersion: 1.0.0
